---
language: node_js
node_js:
  - "5.4.0"

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"
  - "npm install -g npm@^2"


install:
  - npm install -g bower
  - chmod +x .travis/push.sh
  - npm install
  - bower install
  - npm install -g ember-cli
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - ember install:addon ember-cli-github-pages
  - .travis/push.sh

script:
  - npm test
env:
  global:
    secure: GLzk48tAYIPmUq6gj51xr6wJ8tSM/B4hRXPcVniWPg8STfiCQhZ3ZM8h4YjRro5JLW/PxPxn7aonXKnZ+jXsAzAeKKxFV/yUXvIYgmuF0zCYmKYHp4p8juCt7OU0hjrzbrKBZyPDOQ2l72U6Sz6uWEnRJ48Kc6EYXMk4Y2Dzrex7jg8rF5lUj9VSaHPHO2LR0W6Iq97WGLHwRgAeUV7YMvpkSu5D6OSHBZeSZAjmxyqyhbhp/PVPgdNDH4TlBsY8NLUZ60R8HSMV/RFX1quAjGKs/DYZ0/RTBT3ublKz5D/CizKU8mZNgZyGhrnHoSMAmbSy/Trc91UqjBKyku8CFO0CwRhjsjtCZKpfUCcGTjw6Zo9qyo9y6YPMsJ4miKuzcr6g5xLIZ4+fOxZZkwlfof6c8VggEAxZzoxHadgfV4/DjaksZAxjz95lOkEpUKtsKTLidlsOVEBYT7URcnI5KKCPDhP9o2G4iSoFJhuvTa6/RSas/juc/kPdFejuQpX33OkU1Ds7amtshaAW5UA+ATfoR7HgqzqkBLr9/YWbV6XWSBW1GabktZnHjIMC2D6L0FvUsUiuDuYKPDmXzx36vJ9SAgD7kRE722iftsiKduoczIjzSozWWxxxt6G6Ckk4HlrVb1+IA8PzNGyV80EOkx42a/tnVOZJeCIt1YWqoZw=